# Netlify configuration for Hydrogen deployment
# Following https://github.com/netlify/hydrogen-template/blob/main/netlify.toml

[build]
  command = "DEPLOY_TARGET=netlify pnpm run build"
  publish = "dist/client"

[dev]
  command = "pnpm run dev"

# Set immutable caching for static files, because they have fingerprinted filenames
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31560000, immutable"
