/**
 * Custom Netlify Edge Function for Hydrogen.
 * This handler integrates Hydrogen's context with Netlify Edge Functions,
 * replacing the default handler generated by @netlify/vite-plugin-react-router.
 *
 * This file is used as the entry point for Netlify Edge Functions when
 * DEPLOY_TARGET=netlify is set during build.
 */

import * as remixBuild from "virtual:react-router/server-build";
import { storefrontRedirect } from "@shopify/hydrogen";
import { createRequestHandler } from "react-router";
import { createHydrogenRouterContext } from "~/.server/context";
import { buildEnvFromNetlify } from "~/lib/env.server";

/**
 * Edge Function handler for Netlify.
 * Creates the Hydrogen context and handles the request using React Router.
 *
 * @param request - The incoming HTTP request
 * @param _netlifyContext - The Netlify context (unused, we build our own env)
 * @returns The HTTP response
 */
export default async function handler(
    request: Request,
    _netlifyContext: unknown,
): Promise<Response> {
    try {
        console.log(`[Edge] ${request.method} ${request.url}`);

        // Build environment from Netlify globals
        const env = buildEnvFromNetlify();

        // Create Hydrogen context with storefront, session, weaverse, etc.
        const hydrogenContext = await createHydrogenRouterContext(request, env);

        console.log(
            "[Edge] Context created. Storefront:",
            Boolean(hydrogenContext.storefront),
            "Weaverse:",
            Boolean(hydrogenContext.weaverse),
        );

        // Create the React Router request handler
        const routeHandler = createRequestHandler(
            remixBuild,
            process.env.NODE_ENV,
        );

        // Handle the request with Hydrogen context as load context
        const response = await routeHandler(
            request,
            // Cast to satisfy React Router's type expectations
            hydrogenContext as Parameters<typeof routeHandler>[1],
        );

        // Commit session cookie if changes are pending
        if (hydrogenContext.session.isPending) {
            response.headers.set(
                "Set-Cookie",
                await hydrogenContext.session.commit(),
            );
        }

        // Handle 404s with Shopify storefront redirects
        if (response.status === 404) {
            return storefrontRedirect({
                request,
                response,
                storefront: hydrogenContext.storefront,
            });
        }

        return response;
    } catch (error) {
        console.error("[Edge] Error:", error);
        return new Response("An unexpected error occurred", {
            status: 500,
        });
    }
}

/**
 * Netlify Edge Function configuration.
 * This is used when deploying directly as an Edge Function.
 */
export const config = {
    name: "Hydrogen SSR Handler",
    path: "/*",
    excludedPath: ["/.netlify/*", "/assets/*"],
};
