name: CI

on:
    pull_request:
    push:
        branches:
            - master
            - main
            - staging
            - 'dev/*'
            - 'fix/*'
        paths-ignore:
            - '**.md'
            - '**.txt'
            - 'LICENSE'

env:
    CI: true
    # Make sure we disable husky as it might interfere with some operations here
    HUSKY: 0
    # Storefront config.
    SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
    PUBLIC_STORE_DOMAIN: ${{ secrets.PUBLIC_STORE_DOMAIN }}
    PUBLIC_STOREFRONT_API_TOKEN: ${{ secrets.PUBLIC_STOREFRONT_API_TOKEN }}
    WEAVERSE_PROJECT_ID: ${{ secrets.WEAVERSE_PROJECT_ID }}
    WEAVERSE_API_KEY: ${{ secrets.WEAVERSE_API_KEY }}
    JUDGEME_PRIVATE_API_TOKEN: ${{ secrets.JUDGEME_PRIVATE_API_TOKEN }}
    KLAVIYO_PRIVATE_API_TOKEN: ${{ secrets.KLAVIYO_PRIVATE_API_TOKEN }}
    PUBLIC_GOOGLE_GTM_ID: ${{ secrets.PUBLIC_GOOGLE_GTM_ID }}
    PUBLIC_SHOPIFY_INBOX_SHOP_ID: ${{ secrets.PUBLIC_SHOPIFY_INBOX_SHOP_ID }}
    SHOPIFY_ADMIN_API_TOKEN: ${{ secrets.SHOPIFY_ADMIN_API_TOKEN }}



jobs:
    lint:
        name: 📋 Lint
        runs-on: ubuntu-latest
        steps:
            - name: 🕶️ Checkout repository
              uses: actions/checkout@v6

            - name: 🚀 Bootstrap
              uses: ./.github/common/bootstrap

            - name: 📋 Lint
              run: pnpm run biome

    typecheck:
        name: ✅ Typecheck
        runs-on: ubuntu-latest
        steps:
            - name: 🕶️ Checkout repository
              uses: actions/checkout@v6

            - name: 🚀 Bootstrap
              uses: ./.github/common/bootstrap

            - name: ✅ Typecheck
              run: pnpm run typecheck

    build:
        name: 🔨 Build
        needs: [lint, typecheck]
        runs-on: ubuntu-latest
        steps:
            - name: 🕶️ Checkout repository
              uses: actions/checkout@v6

            - name: 🚀 Bootstrap
              uses: ./.github/common/bootstrap

            - name: 🔬 Verify integrity
              run: npm audit signatures

            - name: 🔨 Build all
              run: pnpm run build

    test:
        name: 🧪 Test
        needs: [lint, typecheck]
        runs-on: ubuntu-latest
        steps:
            - name: 🕶️ Checkout repository
              uses: actions/checkout@v6

            - name: 🚀 Bootstrap
              uses: ./.github/common/bootstrap

            - name: 🧪 Test
              run: pnpm run test:coverage

            - name: 🦺 Codecov coverage reports
              if: ${{ !cancelled() }}
              uses: codecov/codecov-action@v5
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  slug: filiphsps/pouched-hydrogen

            - name: 🦺 Upload test results to Codecov
              if: ${{ !cancelled() }}
              uses: codecov/test-results-action@v1
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  slug: filiphsps/pouched-hydrogen
